export enum CategoryType {
  MENS_SINGLES = "MENS_SINGLES",
  WOMENS_SINGLES = "WOMENS_SINGLES",
  MENS_DOUBLES = "MENS_DOUBLES",
  WOMENS_DOUBLES = "WOMENS_DOUBLES",
  MIXED_DOUBLES = "MIXED_DOUBLES",
  CUSTOM = "CUSTOM"
}

export enum TournamentFormat {
  SINGLE_ELIMINATION = "SINGLE_ELIMINATION",
  DOUBLE_ELIMINATION = "DOUBLE_ELIMINATION",
  ROUND_ROBIN = "ROUND_ROBIN",
  GROUP_KNOCKOUT = "GROUP_KNOCKOUT",
  SWISS = "SWISS",
  MULTI_STAGE = "MULTI_STAGE"
} 