export interface BaseResponseDTO {
  id: string;
  created_at: string;
  updated_at: string;
}

export interface AuditableResponseDTO extends BaseResponseDTO {
  created_by?: string;
  updated_by?: string;
}

// Request DTOs don't include id, created_at, or updated_at as they are generated by the system
export interface BaseRequestDTO {
  // Common request properties if any
}

export interface AuditableRequestDTO extends BaseRequestDTO {
  // Auditable request properties if any
} 